[package]
name = "sha256-n"
version = "0.1.0"
edition = "2021"
authors = ["Chloethedev <chloe@marmaj.org>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = "0.10.29"
rand = "0.8.5"
hex = "0.4.1"
